# Generated by Django 5.2 on 2025-11-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL Field')),
                ('url_type', models.CharField(choices=[('document', 'Document'), ('blog', 'Blog'), ('other', 'Other')], verbose_name='URL type')),
            ],
        ),
    ]
